apiVersion: v1
data:
  application: |
    {
      "tcpAddr": ":80"
    }
  myk8s-worker: |-
    {
        "provisioning": {
          "connectionString": "HostName=thingspro-IoTHub-newTwin.azure-devices.net;DeviceId=garyaid1;SharedAccessKey=OhcuosgIuI8gSrpV7ND2N2r7Iuo+KvaH3aoaDLStaEY=",
          "authenticationType": "symmetricKey",
          "enable": true,
          "supportTwin": true,
          "retryInterval": 10,
          "keepAlive": 10,
          "protocol": {
            "protocol": "mqtt",
            "port": 8883
          }
        }
      }
  myk8s-worker2: |-
    {
        "provisioning": {
          "connectionString": "HostName=thingspro-IoTHub-newTwin.azure-devices.net;DeviceId=garyaid2;SharedAccessKey=3CewtRtIzSEwLgRkpu6tJbyYoEQJiq5ljHTvT2XfgZc=",
          "authenticationType": "symmetricKey",
          "enable": true,
          "supportTwin": true,
          "retryInterval": 10,
          "keepAlive": 10,
          "protocol": {
            "protocol": "mqtt",
            "port": 8883
          }
        }
      }
  product: |-
    {
        "services": [
            "azuredevice"
        ]
    }
  twin: |-
    {
      "properties": [],
      "selections": {},
      "connectionID": "azuredevice-1",
      "enable": true
    }
kind: ConfigMap
metadata:
  name: azure-config-87c74td2f4
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: northbound
  name: northbound-daemon
spec:
  selector:
    matchLabels:
      app: northbound
  template:
    metadata:
      labels:
        app: northbound
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: bibbylong/iiot-clouds:2.2.0-armhf
        name: cloud
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/thingspro/cloud/env/product.json
          name: azure-volume
          subPath: product
        - mountPath: /var/thingspro/cloud/setting/.configuration
          name: azure-volume
          subPath: application
        - mountPath: /var/thingspro/cloud/setting/twin/azuredevice-1.json
          name: azure-volume
          subPath: twin
        - mountPath: /var/thingspro/cloud/setting/azuredevice/azuredevice.json
          name: connection-volume
      initContainers:
      - command:
        - sh
        - -c
        - cat /var/thingspro/${NODE_NAME} > /tmp/azuredevice.json
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: busybox:1.28
        name: node2pod
        volumeMounts:
        - mountPath: /tmp/azuredevice.json
          name: connection-volume
        - mountPath: /var/thingspro
          name: azure-volume
      volumes:
      - configMap:
          name: azure-config-87c74td2f4
        name: azure-volume
      - hostPath:
          path: /tmp/azuredevice.json
          type: FileOrCreate
        name: connection-volume
