apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-config
  namespace: default
data:
  product: "{\"services\":[\"azuredevice\"]}"
  application: "{\"tcpAddr\":\":80\"}"
  provisioning: "{\"provisioning\":{\"authenticationType\":\"symmetricKey\",\"connectionString\":\"HostName=thingspro-IoTHub-newTwin.azure-devices.net;DeviceId=garyaid1;SharedAccessKey=OhcuosgIuI8gSrpV7ND2N2r7Iuo+KvaH3aoaDLStaEY=\",\"enable\":false,\"supportTwin\":true,\"retryInterval\":10,\"keepAlive\":10,\"protocol\":{\"protocol\":\"mqtt\",\"port\":8883}}}"
  twin: "{\"properties\":[],\"selections\":{},\"connectionID\":\"azuredevice-1\",\"enable\":false}"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: northbound-daemon
  labels:
    app: northbound
spec:
  selector:
    matchLabels:
      app: northbound
  template:
    metadata:
      labels:
        app: northbound
    spec:
      containers:
      - name: cloud
        image: bibbylong/iiot-clouds:2.2.0-armhf
        ports:
        - containerPort: 80
        volumeMounts:
          - name: azure-volume
            mountPath: /var/thingspro/cloud/env/product.json
            subPath: product
          - name: azure-volume
            mountPath: /var/thingspro/cloud/setting/.configuration
            subPath: application
          - name: azure-volume
            mountPath: /var/thingspro/cloud/setting/azuredevice/azuredevice.json
            subPath: provisioning
          - name: azure-volume
            mountPath: /var/thingspro/cloud/setting/twin/azuredevice-1.json
            subPath: twin
      volumes:
      - name: azure-volume
        configMap:
          name: azure-config